# Generated by Django 3.0 on 2021-07-18 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('year_of_warranty', models.PositiveIntegerField(default=1)),
                ('finance_plan', models.CharField(default='unavailable', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='carDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=30)),
                ('car_brand', models.CharField(max_length=30)),
                ('production_year', models.PositiveIntegerField()),
                ('car_body', models.CharField(max_length=60)),
                ('engine_type', models.CharField(max_length=40)),
                ('car_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carsinfo.CarPlan')),
            ],
        ),
        migrations.CreateModel(
            name='carAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carsinfo.carDetails')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
